version: '3'

services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/jenkins:/var/jenkins_home
    networks:
      - cicd
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cicd
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - 3100:3100
    volumes:
     - ./data/loki/loki-config.yml:/etc/loki/loki-config.yaml
    command: -config.expand-env=true -config.file=/etc/loki/loki-config.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - cicd

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - /var/log:/var/log
      - ./data/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    networks:
      - cicd
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0:0"
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - cicd

volumes:
  jenkins: {}
  prometheus: {}
  loki: {}
  promtail: {}
  grafana: {}

networks:
  cicd:
    name: cicd
    external: false