services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./storage:/opt/www/storage
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d
      - ./config/certs:/etc/nginx/certs
      - ./config/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      # - ./certbot/certs/live:/etc/letsencrypt/live
      # - ./certbot/certs/archive:/etc/letsencrypt/archive
    networks:
      - nginx
    entrypoint: ["sh", "-c", "while :; do sleep infinity; done"]
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    volumes:
      - ./storage:/srv
      - ./filebrowser/database:/database
      - ./filebrowser/config:/config
    # ports:
    #   - 127.0.0.1:8080:80
    networks:
      - nginx
    restart: always

networks:
  nginx:
    driver: bridge
