upstream jenkins {
    server 192.168.171.130:8080;
    #server host.docker.internal:8080;
}

server {
        listen 80;
        server_name www.local.jenkins.com local.jenkins.com;
	return 301 https://local.jenkins.com$request_uri;
        access_log off;
}

server {
    listen 443 ssl;
    server_name www.local.jenkins.com local.jenkins.com;

    ssl_certificate /etc/nginx/certs/jenkins-fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/jenkins-privkey.pem;

    access_log /var/log/nginx/jenkins-access.log;
    error_log /var/log/nginx/jenkins-error.log error;

    location / {
        proxy_pass http://jenkins;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
