upstream vibekanbanclient {
    server 192.168.171.130:30001;
}

upstream vibekanbanhost {
    server 192.168.171.130:3000;
}

server {
        listen 80;
        server_name local.vibekanban.com;
        return 301 https://$host$request_uri;
        access_log off;
}

server {
    listen 443 ssl;
    server_name local.vibekanban.com;

    ssl_certificate /etc/nginx/certs/vibekanban-fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/vibekanban-privkey.pem;

    access_log /var/log/nginx/vibekanban-access.log;
    error_log /var/log/nginx/vibekanban-error.log error;

    location / {
        proxy_pass http://vibekanbanclient;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
        listen 80;
        server_name local.vibekanbanhost.com;
        return 301 https://$host$request_uri;
        access_log off;
}

server {
    listen 443 ssl;
    server_name local.vibekanbanhost.com;

    ssl_certificate /etc/nginx/certs/vibekanban-fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/vibekanban-privkey.pem;

    access_log /var/log/nginx/vibekanbanhost-access.log;
    error_log /var/log/nginx/vibekanbanhost-error.log error;

    location / {
        proxy_pass http://vibekanbanhost;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
