- name: Pull Docker images
  docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - nhq051201/demo

- name: Run containers
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: started
    ports:
      - "{{ item.ports }}"
  loop:
    - { name: "demo1", image: "nhq051201/demo", ports: "3000:3000" }